
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use block body for methods", Justification = "Why?", Scope = "member", Target = "~M:Software9119.Aid.Collection.CollectionExtensions.ToReadOnlyCollection``1(System.Collections.Generic.IEnumerable{``0})~System.Collections.ObjectModel.ReadOnlyCollection{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Not my style.", Scope = "member", Target = "~M:Software9119.Aid.Collection.CollectionExtensions.ToIList``1(System.Collections.Generic.IEnumerable{``0},System.Boolean)~System.Collections.Generic.IList{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use block body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Object.ObjectExtensions.IsNull(System.Object)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use block body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Collection.CollectionExtensions.ReturnNull``1(System.Collections.Generic.IEnumerable{``0},System.Boolean)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use block body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Collection.CollectionExtensions.ReturnEmpty``1(System.Collections.Generic.IEnumerable{``0},System.Boolean)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Collection.CollectionExtensions.ToIList``1(System.Collections.Generic.IEnumerable{``0})~System.Collections.Generic.IList{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use block body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Collection.CollectionExtensions.EmptyRODict``2~System.Collections.ObjectModel.ReadOnlyDictionary{``0,``1}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Type.TypeAide.IsUnManaged(System.Type)~System.Boolean")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "namespace", Target = "~N:Software9119.Aid.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Collection.CollectionExtensions.AsOrTo``2(System.Collections.Generic.IEnumerable{``0},System.Boolean)~``1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Collection.CollectionExtensions.AsReadOnlyDictionary``2(System.Collections.Generic.Dictionary{``0,``1},System.Boolean)~System.Collections.ObjectModel.ReadOnlyDictionary{``0,``1}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Collection.CollectionExtensions.ToReadOnlyDictionary``2(System.Collections.Generic.IEnumerable{``0},System.Func{``0,``1},System.Boolean)~System.Collections.ObjectModel.ReadOnlyDictionary{``1,``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Collection.CollectionExtensions.ToReadOnlyDictionary``3(System.Collections.Generic.IEnumerable{``0},System.Func{``0,``1},System.Func{``0,``2},System.Boolean)~System.Collections.ObjectModel.ReadOnlyDictionary{``1,``2}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Object.ObjectAide.NullableOrResult``2(``0,System.Func{``0,``1})~System.Nullable{``1}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Object.ObjectAide.NullOrResult``2(``0,System.Func{``0,``1})~``1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Object.ObjectAide.NullableOrResult``2(``0,System.Func{``0,``1})~System.Nullable{``1}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Object.ObjectAide.NullOrResult``2(``0,System.Func{``0,``1})~``1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Object.ObjectExtensions.IsNull(System.Object)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2008:Do not create tasks without passing a TaskScheduler", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Parallel.AsyncAide.RunSync(System.Func{System.Threading.Tasks.Task})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2008:Do not create tasks without passing a TaskScheduler", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Parallel.AsyncAide.RunSync``1(System.Func{System.Threading.Tasks.Task{``0}})~``0")]