
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Not my style.", Scope = "member", Target = "~M:Software9119.Aid.Collection.CollectionExtensions.ToIList``1(System.Collections.Generic.IEnumerable{``0},System.Boolean)~System.Collections.Generic.IList{``0}")]
[assembly: SuppressMessage("Style", "IDE0022:Use block body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Object.ObjectExtensions.IsNull(System.Object)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0022:Use block body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Collection.CollectionExtensions.EmptyRODict``2~System.Collections.ObjectModel.ReadOnlyDictionary{``0,``1}")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Type.TypeAide.IsUnManaged(System.Type)~System.Boolean")]

[assembly: SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "namespace", Target = "~N:Software9119.Aid.Object")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Collection.CollectionExtensions.AsOrTo``2(System.Collections.Generic.IEnumerable{``0},System.Boolean)~``1")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Collection.CollectionExtensions.AsReadOnlyDictionary``2(System.Collections.Generic.Dictionary{``0,``1},System.Boolean)~System.Collections.ObjectModel.ReadOnlyDictionary{``0,``1}")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Collection.CollectionExtensions.ToReadOnlyDictionary``2(System.Collections.Generic.IEnumerable{``0},System.Func{``0,``1},System.Boolean)~System.Collections.ObjectModel.ReadOnlyDictionary{``1,``0}")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Collection.CollectionExtensions.ToReadOnlyDictionary``3(System.Collections.Generic.IEnumerable{``0},System.Func{``0,``1},System.Func{``0,``2},System.Boolean)~System.Collections.ObjectModel.ReadOnlyDictionary{``1,``2}")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Object.ObjectAide.NullableOrResult``2(``0,System.Func{``0,``1})~System.Nullable{``1}")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Object.ObjectAide.NullOrResult``2(``0,System.Func{``0,``1})~``1")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Object.ObjectAide.NullableOrResult``2(``0,System.Func{``0,``1})~System.Nullable{``1}")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Object.ObjectAide.NullOrResult``2(``0,System.Func{``0,``1})~``1")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Object.ObjectExtensions.IsNull(System.Object)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0022:Use block body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Object.ObjectAide.Matches(System.Object,System.Object)~System.Boolean")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Enumerable.EnumerableExtensions.ToDictionary``2(System.Collections.Generic.IEnumerable{``1},System.Func{``1,``0},System.Int32)~System.Collections.Generic.Dictionary{``0,``1}")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Enumerable.EnumerableExtensions.ToDictionary``3(System.Collections.Generic.IEnumerable{``2},System.Func{``2,``0},System.Func{``2,``1},System.Int32)~System.Collections.Generic.Dictionary{``0,``1}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Enumerable.EnumerableExtensions.ToArray``1(System.Collections.Generic.IEnumerable{``0},System.Int32)~``0[]")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Enumerable.EnumerableExtensions.ToList``1(System.Collections.Generic.IEnumerable{``0},System.Int32)~System.Collections.Generic.List{``0}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Enumerable.EnumerableExtensions.ToDictionary``3(System.Collections.Generic.IEnumerable{``2},System.Func{``2,``0},System.Func{``2,``1},System.Int32)~System.Collections.Generic.Dictionary{``0,``1}")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "<Pending>", Scope = "member", Target = "~M:Software9119.Aid.Enumerable.EnumerableExtensions.ToList``1(System.Collections.Generic.IEnumerable{``0},System.Int32)~System.Collections.Generic.List{``0}")]
